# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/reshmasiripangi-commits/flyrank-ml-internship-starter/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

Rule:

If a content page has high search volume and low competition, it should receive a higher action score because it has a better chance of gaining traffic.

Reason Codes:

HIGH_SEARCH_VOLUME
LOW_COMPETITION
GOOD_OPPORTUNITY

In [6]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import pandas as pd

df = pd.read_csv("../../data/processed/refresh_feature_vector.csv")

def get_reason(row):
    if row["search_volume"] > 50 and row["competition"] < 0.3:
        return "GOOD_OPPORTUNITY"
    elif row["search_volume"] > 50:
        return "HIGH_SEARCH_VOLUME"
    else:
        return "LOW_PRIORITY"

df["reason_code"] = df.apply(get_reason, axis=1)

df[["search_volume","competition","reason_code"]].head()

   search_volume  competition       reason_code
0           10.0         0.67      LOW_PRIORITY
1           90.0         0.01  GOOD_OPPORTUNITY
2            0.0         0.00      LOW_PRIORITY
3           10.0         0.00      LOW_PRIORITY
4            0.0         0.00      LOW_PRIORITY

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

Each content item receives a score based on search volume and competition.

Higher search volume increases the score.

Higher competition decreases the score.

The ranked list is sorted from highest score to lowest score.

In [7]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
df["score"] = df["search_volume"] * (1 - df["competition"])

ranked = df.sort_values("score", ascending=False)

ranked.head(20)
ranked.to_csv("../../outputs/baseline_action_score.csv", index=False)

print("CSV Saved Successfully")

CSV Saved Successfully

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

The highest ranked pages generally have high search volume and low competition.

These pages are good candidates for optimization.

The ranking is based on a simple baseline rule and may not capture all business factors.

In [8]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
ranked[[
    "content_id",
    "search_volume",
    "competition",
    "score",
    "reason_code"
]].head(20)

,content_id,search_volume,competition,score,reason_code
12140,content_ef99c4abd9ab,74000.0,0.08,68080.0,GOOD_OPPORTUNITY
6972,content_bf67a444faef,60500.0,0.11,53845.0,GOOD_OPPORTUNITY
28282,content_454cc6654c6e,60500.0,0.11,53845.0,GOOD_OPPORTUNITY
18701,content_deb54e9e19cd,60500.0,0.13,52635.0,GOOD_OPPORTUNITY
17907,content_5ec29ae79c60,60500.0,0.13,52635.0,GOOD_OPPORTUNITY
16005,content_83e3da1394ac,49500.0,0.03,48015.0,GOOD_OPPORTUNITY
22788,content_ee4630879d03,49500.0,0.06,46530.0,GOOD_OPPORTUNITY
8055,content_cd6760921db8,49500.0,0.08,45540.0,GOOD_OPPORTUNITY
13502,content_f76ccf7a7834,49500.0,0.23,38115.0,GOOD_OPPORTUNITY
8002,content_c841193dc692,40500.0,0.09,36855.0,GOOD_OPPORTUNITY
15923,content_84fe9d0a707a,40500.0,0.10,36450.0,GOOD_OPPORTUNITY
5287,content_8ca50876b0df,40500.0,0.10,36450.0,GOOD_OPPORTUNITY
2991,content_6f6a4e56098c,33100.0,0.00,33100.0,GOOD_OPPORTUNITY
2553,content_eb1510f4b5f1,33100.0,0.10,29790.0,GOOD_OPPORTUNITY
25812,content_f04ea036f597,33100.0,0.12,29128.0,GOOD_OPPORTUNITY
9217,content_12e48d4b449d,27100.0,0.04,26016.0,GOOD_OPPORTUNITY
3646,content_6b41450ae50c,27100.0,0.06,25474.0,GOOD_OPPORTUNITY
2074,content_6ef3dcb7be11,27100.0,0.06,25474.0,GOOD_OPPORTUNITY
18336,content_82f8b592944a,22200.0,0.05,21090.0,GOOD_OPPORTUNITY
25780,content_b40e32d5df10,22200.0,0.05,21090.0,GOOD_OPPORTUNITY

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

Possible weak picks:

Some pages may have high search volume but very high competition.

Some pages may receive a good score even if they have poor historical performance.

No future information or target labels were used while calculating the score, so there is no data leakage.

In [9]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
weak = ranked.tail(10)

weak[[
    "content_id",
    "search_volume",
    "competition",
    "score"
]]

                 content_id  search_volume  competition  score
2      content_9aa793d4d895            0.0          0.0    0.0
29975  content_bdee2164f576            0.0          0.0    0.0
15007  content_8de1380b5e5f            0.0          0.0    0.0
29973  content_4be930227848            0.0          0.0    0.0
29972  content_1db0d204d42f            0.0          0.0    0.0
29986  content_677c622c0bfb            0.0          0.0    0.0
29984  content_a6568a7c07d7            0.0          0.0    0.0
15     content_689414059706            0.0          0.0    0.0
14     content_91067a14431a            0.0          0.0    0.0
19     content_af865035b328           30.0          1.0    0.0

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.